site_name: Dai.JPro
pages:
    - cpp: learning-cpp.md
    - scala: scala-sbt-usage.md
    - python: python.md
    - algorithm: algorithm.md
    - kernel: kernel.md
    - compile: compilation.md
    - data analysis: data-analysis.md
    - mathematics: mathematics.md
theme: readthedocs
